Hw4
SachkovaYuliia/nodejs24_hw_-SachkovaYuliia- pull request #4
Opened 2024-05-06 22:21 UTC by SachkovaYuliia

2024-05-07 09:06 UTC, evhenious commented on utils/logger.js
> +const { Readable, Writable } = require('stream');
Так, просто цікаво - ти ніде не використовуєш ці класи, для чого вони тут? Зазвичай, старайся не імпортувати речі які непотрібні

2024-05-07 09:10 UTC, evhenious commented on utils/logger.js
> +    const logsDir = path.join(__dirname, 'logs');
Перевірка наявності папки для логів і створення - ОК. Тільки зверни увагу де в тебе створюється папка - всередині папки utils. А за умовами задачі вона має бути в корні нашого репозиторія - на одному рівні з utils, не в середині :)

2024-05-07 09:13 UTC, evhenious commented on utils/logger.js
> +    const infoLogFile = path.join(logsDir, 'info.log');
Немає необхідності створювати ці файи заздалегіть. Згадай заняття, ми це розбирали - коли відкриваєш файлстрім на запис, він автоматом створить файл призначення, якщо його іще немає

2024-05-07 09:18 UTC, evhenious commented on utils/logger.js
> +module.exports = {
Stop, hammertime. Чому в нас міняються експорти?

В завданні ані слова про те що логгер буде експортувати щось інше (чи додаткове) до того, що ми вже зробили в попередніх домашках. Всі зміни тільки всередині

2024-05-07 09:19 UTC, evhenious commented on utils/logger.js
> +process.on('beforeExit', () => {
Закриття стрімов ++

2024-05-07 09:25 UTC, evhenious commented on utils/logger.js
> +function logMessage(stream, message) {
Ця функція правильна, не міняй - просто використай інакше ніж у тебе зараз

2024-05-07 09:25 UTC, evhenious commented on utils/logger.js
> +function logInfo(message) {
Передивись будь ласка текст завдання, особливо пункт під цифрою 2 :) 

там прямі інструкції (навіть з прикладом) про те в який момент і які саме месаджі потрапляють в файлстріми. Не придумуй чогось стороннього, зроби будь ласка 1-в-1 як написано :)

2024-05-07 09:27 UTC, evhenious requested changes
Передивись будь ласка текст завдання, особливо пункт під цифрою 2, і дороби завдання так щоб твоя імплементація відповідала завданню

2024-05-07 09:36 UTC, evhenious commented on utils/logger.js
> +const infoStream = fs.createWriteStream(path.join(__dirname, 'logs', 'info.log'), { flags: 'a' });
Класно що ти одразу відкриваєш стрім на запис з ключем А - таким чином ти не затираєш старі логи, а додаєш нове до існуючого 👍

2024-05-10 06:35 UTC, SachkovaYuliia commented on utils/logger.js
> +function logInfo(message) {
Тобто додати в функцію умову, передбачивши куди писати, типу так: function logInfo(message) {
    if (process.env.LOG_LEVEL === 'INFO' ) {
        console.log(message);
    } else {
    logMessage(infoStream, message);
}

2024-05-10 07:00 UTC, SachkovaYuliia commented on utils/logger.js
> +module.exports = {
Тобто взагалі не експортувати функції? Я так розуміла, що функції всі обов'язково експортувати, щоб використовувати не лише локально. Ок.

2024-05-10 07:01 UTC, SachkovaYuliia commented on utils/logger.js
> +    const infoLogFile = path.join(logsDir, 'info.log');
Ок, дякую.

2024-05-10 07:01 UTC, SachkovaYuliia commented on utils/logger.js
> +    const logsDir = path.join(__dirname, 'logs');
ок, дякую.

2024-05-10 07:02 UTC, SachkovaYuliia commented on utils/logger.js
> +const { Readable, Writable } = require('stream');
Було багато спроб)) витру.

2024-05-10 07:07 UTC, SachkovaYuliia commented on utils/logger.js
> +function logMessage(stream, message) {
Ok

2024-05-10 07:43 UTC, SachkovaYuliia commented on utils/logger.js
> +function logInfo(message) {
Перечитала завдання ще раз і розумію, що не розумію напевне вірно. Тобто всі методи завжди мають писати стріми,але якщо метод співпадає з env var, тоді ще плюс має писати в консоль, чи ні? function logInfo(message) {
  if (process.env.LOG_LEVEL === 'INFO') {
    console.log(message);
    logMessage(infoStream, message);
  } else {
  logMessage(infoStream, message);
  }
}

2024-05-10 07:43 UTC, SachkovaYuliia commented on utils/logger.js
> +function logInfo(message) {
все одно нічого не пише в консоль

2024-05-10 07:49 UTC, SachkovaYuliia commented on utils/logger.js
> +const { Readable, Writable } = require('stream');
а чому коли я переношу в мейн const fs = require('fs');
const path = require('path'); не працює?

2024-05-10 09:04 UTC, evhenious commented on utils/logger.js
> +const { Readable, Writable } = require('stream');
А для чого ти це переносиш в мейн? Кожен імпорт має сенс тільки в контексті поточного файла. Іншими словами, ти імпортуєш fs для того щоб використати цей модуль **саме тут**, в файлі `logger.js`. Інакше ніяк

2024-05-10 09:06 UTC, evhenious commented on utils/logger.js
> +module.exports = {
> функції всі обов'язково експортувати

абсолютно НІ. В кожному модулі є речі "для внутрішнього використання" і те, що потбібно десь ззовні. Експортувати потрібно тільки те що точно потрібно десь іще. Це нормально мати функції які доступні тільки всередині якогось модуля.

2024-05-10 09:10 UTC, evhenious commented on utils/logger.js
> +function logInfo(message) {
Так, всі три методи нашого логгера завжди пишуть месаджі в файлстрім, це незалежно від лог левела який ми виставимо в конфігу. 
Але при цьому має повністю зберігтись вже існуюча логіка - параметр LOG_LEVEL продовжує регулювати які з методів логгера будуть писати в термінал

2024-05-10 11:12 UTC, SachkovaYuliia commented on utils/logger.js
> +module.exports = {
супер, дякую!

2024-05-10 11:13 UTC, SachkovaYuliia commented on utils/logger.js
> +function logInfo(message) {
Блін, ти ж писав, що потрібно допилити логер!!! Здається зрозуміла.))) Нарешті!

2024-05-10 11:15 UTC, SachkovaYuliia commented on utils/logger.js
> +function logInfo(message) {
Переробила, але пише лише чомусь ерор. Не розумію чому.

2024-05-10 12:34 UTC, merged