added simple server code
SachkovaYuliia/nodejs24_hw_-SachkovaYuliia- pull request #5
Opened 2024-05-12 18:40 UTC by SachkovaYuliia

2024-05-12 19:21 UTC, evhenious commented on config/default.js
> +  colorsEnabled: +process.env.COLORS_ENABLED || 1, // або значення із енва, або дефолтне якщо в енві не задано
Просто зроби у себе локально файлік .env, і пропиши в нього значення які потрібні тобі в даний момент. Не треба нічого міняти тут :)

2024-05-12 19:22 UTC, evhenious commented on server.js
> +const logger = require('./utils/logger')('server');
👍

2024-05-12 19:41 UTC, evhenious requested changes
Маєш дві проблеми:
1. Твій код впаде якщо звернутись на ендпоінт /healthcheck. Тобі завдання - вичислити де проблема, і виправити. 
2. Ти знов стартанула бранчу з домашкою не з найсвіжішого стану бранчі main, а з того що у тебе залишалось крайнім.

2024-05-12 20:06 UTC, SachkovaYuliia commented on config/default.js
> +  colorsEnabled: +process.env.COLORS_ENABLED || 1, // або значення із енва, або дефолтне якщо в енві не задано
не працює той файлик:(

2024-05-12 20:44 UTC, SachkovaYuliia commented on config/default.js
> +  colorsEnabled: +process.env.COLORS_ENABLED || 1, // або значення із енва, або дефолтне якщо в енві не задано
1. щодо Твій код впаде якщо звернутись на ендпоінт /healthcheck. Тобі завдання - вичислити де проблема, і виправити: або прописати resp.end('healthcheck passed'); або  //         const filePath = path.join(process.cwd(), 'static', 'index.html');
//         const file = fs.createReadStream(filePath);
       
//         file.pipe(resp);
//         return;
2. щодо Ти знов стартанула бранчу з домашкою не з найсвіжішого стану бранчі main, а з того що у тебе залишалось крайнім. , то виправляла,  створила ще кучу гілок, по. ітогу все зникло, якщо завтра встигну, буду ввечорі розбиратись. Все, ми з гітхаб офіційно не друзі).

2024-05-12 20:48 UTC, evhenious commented on config/default.js
> +  colorsEnabled: +process.env.COLORS_ENABLED || 1, // або значення із енва, або дефолтне якщо в енві не задано
>  не працює той файлик:(

Правильно. А що треба зробити для того щоб він запрацював? Пакети dotenv + config використати в сервері )

2024-05-13 19:39 UTC, evhenious commented on config/default.js
> +  port: 3003
ну і просто в ідеалі якщо - брати це значення із енва :) але нехай то вже залишається для іншої історії

2024-05-13 19:47 UTC, evhenious commented on server.js
> +            resp.writeHead(200, { 'content-type': 'text/plain' });
Це також на майбутнє, але - text/plain не дорівнює text/html. Це різні контент типи. І коли ти робиш ` resp.end('healthcheck passed');` - ти повертаєш text/plain, це не html.

2024-05-13 19:48 UTC, evhenious approved these changes

2024-05-13 19:48 UTC, merged